# Generated by Django 5.1.3 on 2024-11-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising', '0002_alter_advertising_budget_alter_advertising_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ads', models.ForeignKey(help_text='the advertising campaign from which the lead learned about the service', null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertising.advertising')),
            ],
        ),
    ]
