# Generated by Django 5.1.3 on 2024-11-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_alter_advertising_budget_alter_advertising_channel_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PotClient',
            new_name='Lead',
        ),
    ]
