# Generated by Django 5.1.3 on 2024-11-28 12:42

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_potclient_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[clients.models.validate_phone_format]),
        ),
    ]
