# Generated by Django 5.1.3 on 2024-11-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
