workflow:
    rules:
        - if: ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME  == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME  == "develop") && $CI_PIPELINE_SOURCE == "merge_request_event"

image: python:3.12

stages:
    - build
    - linters
    - test

build-req:
    stage: build
    script:
        - pip install -r requirements_dev.txt
    artifacts:
        paths:
            - ./
        expire_in: 1 hour

black:
    stage: linters
    script:
        - python3 -m black --diff --check .
    dependencies:
        - build-req

isort:
    stage: linters
    script:
        - python3 -m isort --check-only --diff --profile black .
    dependencies:
        - build-req

flake8:
    stage: linters
    script:
        - python3 -m flake8 .
    dependencies:
        - build-req

mypy:
    stage: linters
    script:
        - python3 -m mypy .
    dependencies:
        - build-req

unittest:
    stage: test
    services:
        - postgres:13.3
    dependencies:
        - build-req
    script:
        - cd crm
        - python3 manage.py test
    variables:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_HOST: $POSTGRES_HOST
        POSTGRES_PORT: $POSTGRES_PORT
        POSTGRES_HOST_AUTH_METHOD: trust
        DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
