workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"

image: python:3.12

stages:
    - linters
    - test

before_script:
    - python -V
    - pip install virtualenv
    - virtualenv .venv
    - source .venv/bin/activate
    - ls -a
    - pip install -r requirements_dev.txt

black:
    stage: linters
    script:
        - python3 -m black --diff --check .

isort:
    stage: linters
    script:
        - python3 -m isort --check-only --diff --profile black .

flake8:
    stage: linters
    script:
        - python3 -m flake8 .

mypy:
    stage: linters
    script:
        - python3 -m mypy .


unittest:
    stage: test
    script:
        - cd crm
        - python3 manage.py test
