services:
  postgres:
    image: postgres:13.3
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - my_network
  app:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "ls &&
             python crm/manage.py migrate &&
             python crm/manage.py loaddata crm/users-fixtures.json && 
             python crm/manage.py runserver 0.0.0.0:8000"
    env_file: ".env"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - my_network

networks:
  my_network:
    driver: bridge