[tool.black]
line-length = 88
force-exclude = '''
/(
    \.venv
  | \.venv_dev
  | migrations
)/
|
(
    .*/apps\.py
  | .*/settings\.py
  | /crm/manage\.py
  | /crm/wsgi\.py
  | /crm/asgi\.py
)
'''

[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true
skip_glob = [
    "**/migrations/*",
    "**/settings.py",
    "**/apps.py",
    "**/.venv/*",
    "**/.venv_dev/*",
    "**wsgi.py",
    "**asgi.py",
    "**manage.py",
]

[tool.mypy]
exclude = [
    ".venv",
    ".venv_dev",
    ".*/migrations/",
    '.*/apps\.py',
    '.*/settings\.py',
    '.*manage\.py',
    '.*wsgi\.py',
    '.*asgi\.py'
]
ignore_missing_imports = true
