# Generated by Django 5.1.3 on 2024-11-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
        ('services', '0002_rename_price_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='advertising budget', max_digits=8),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='channel',
            field=models.CharField(help_text='promotion channel', max_length=100),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='product',
            field=models.ForeignKey(help_text='advertised service', on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
