# Generated by Django 5.1.3 on 2024-11-28 14:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_rename_price_service_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the unique name of the contract', max_length=100, unique=True)),
                ('doc', models.FileField(help_text='the file with the contract document', upload_to='contracts')),
                ('date', models.DateField(auto_now_add=True, help_text='date of conclusion of the contract')),
                ('duration', models.DurationField(default=datetime.timedelta(days=1), help_text='duration of the contract')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('product', models.ForeignKey(help_text='the service provided', on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
